### ISSUE TITLE
Unnecessary dependency on bash

### ISSUE THREAD

**Issue by ncfavier** [actions/upload-pages-artifact#13]
This action sets `shell: bash` when running simple commands, which causes it to fail in environments where bash isn't available instead of falling back to `sh`.

I believe the fix is to ~remove the `shell: bash` lines~ replace `shell: bash` with `shell: sh` for linux and macos, not sure about windows. See the documentation [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell)

**Comment by ncfavier** [comment]
Note that the documentation is faulty here:

> `bash`   The default shell on non-Windows platforms with a fallback to sh. When specifying a bash shell on Windows, the bash shell included with Git for Windows is used.

It does *not* fall back to `sh`. Example failed workflow: https://github.com/ncfavier/1lab/runs/7866004286?check_suite_focus=true#step:7:20

**Comment by yoannchaudet** [comment]
I think you are having issues here because you don't have `bash` in the container you are building in. 

Because `bash` is available on all platforms and the default for non-Windows, I prefer us to keep using it. I suggest you just install it in your container. I am following up with the Actions team to understand what they mean with "[...] with a fallback to sh".

**Comment by ncfavier** [comment]
I know, we're using busybox `sh` in the container to cut down on image size. `sh` is the standard name for the [POSIX shell](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html) and should be available on all environments, even if it's a symlink to another shell. There is no reason to depend on bash for running a simple `tar` command with no fancy substitutions.

**Comment by yoannchaudet** [comment]
Fair enough I take that back. The fallback also does not seem to work if we do specify a `bash`. Outside of testing, we should be good with your suggested PR.

**Comment by rmhrazorhead** [comment]
Does Windows need to specify 'bash'? Yes you can technically install it, but it seems an unnecessary dependency/complication?
