### ISSUE TITLE
Accept multiline input for path parameter

### ISSUE THREAD

**Issue by lobis** [actions/upload-pages-artifact#22]
I have recently started to use this action to automatically build my github pages for one of my repos.

Here is the [actions configuration file](https://github.com/lobis/fractal-explorer/blob/f37554cb3c30a11c7406b9ea6122a5bb05fbcce7/.github/workflows/rust.yml).

My static site requires multiple files. I originally save them to an artifact using the `actions/upload-artifact@v3` action. I use multiline path for this as you can see below.

```
- name: Upload artifact
  uses: actions/upload-artifact@v3
  with:
    name: web-assembly-build
    path: |
      pkg/
      index.html
      src/assets/icon.png
```

Using this action I would love to use a similar syntax to specify the files I need. Using a multiline parameter like above doesn't currently work unless I am missing something.

What I ended up doing is:

```
- name: Upload artifact
  uses: actions/upload-pages-artifact@v1
  with:
    path: "."
```

Which uploads unecessary files.

I think using a multiline parameter would be a great way to specify multiple files so I would like to request it as a new feature. Maybe there is a simple way to specify multiple files that I am unaware of, please let me know.

Thanks!

**Comment by yoannchaudet** [comment]
In the same line of my response [here](https://github.com/actions/upload-pages-artifact/pull/21#issuecomment-1244070254), I think a best approach if for your to create a folder containing all the assets you want to deploy at build time and not delegate that to the deploy time (i.e. what you are after now).

Most static site generators function this way. You would need this too if you wanted to test your changes locally outside of Actions ;)
