### ISSUE TITLE
Upload artifact part does not contain nested directories

### ISSUE THREAD

**Issue by jeertmans** [actions/upload-pages-artifact#25]
Hello,

First, thank you for this great action!

Very recently, I encountered some issue with uploading all the artifacts needed for my website.

To be short, I convert some Jupyter Notebook into an HTML page, which I deploy on my personal website.

When looking at the `tar` step in the action, I see that it only upload `slides/` folder, and `slides/images/` folder (and its content).
However, I also need the content in `slides/media/videos/...` etc.

![image](https://user-images.githubusercontent.com/27275099/192090924-67e3a8de-4f48-4c0a-8800-6ae945ed9e87.png)

If I reimplement the action myself, it works just fine, see https://github.com/jeertmans/manim-tutorial/blob/dd7cd120b09941c5ac5df489896a6cb7522e1464/.github/workflows/pages.yml#L80-L103.

![image](https://user-images.githubusercontent.com/27275099/192090944-7567eb1e-0d65-486d-b88c-011b2980fec0.png)

> NOTE: the exclude patterns are not necessary to make my action work, it just reduces the amount of files uploaded

Do you know why it does not work within your action?

**Comment by gkucmierz** [comment]
I have same problem with `dist/` from vue js app.

**Comment by yoannchaudet** [comment]
@jeertmans Are you sure your `dist` folder did indeed contain the files you were expecting in the archive? There are no reasons for `tar` not to see the files.

If you have a link to a particular commit in your repo where you saw the issue, we can look at it.

**Comment by jeertmans** [comment]
Hi @yoannchaudet , after trying to reproduce the error, it now seems to work fine...

I would swear that it didn't work as expected, but it seems like I was missing something.

Anyway, I think I can close this now, sorry for the inconvenience.

**Comment by elpddev** [comment]
I had the same problem with a vite application. The problem was the `base` property in the `index.html`. 

1. The application html ask for  `./assets/asdf.js`
2. But the application is deployed under a `<user>.github.com/<repo/` meaning the asset deployed is under `/<repo>/`.

Kind of hard to spot because on first glance in the dev tool network tab, it seems the same file name but it gets 404.

Vite docs [suggest](https://vitejs.dev/guide/static-deploy.html#github-pages) to set the `base` attribute to the repo name to fix this.

> Set the correct base in vite.config.js.
> If you are deploying to https://<USERNAME>.github.io/, you can omit base as it defaults to '/'.
> 
> If you are deploying to https://<USERNAME>.github.io/<REPO>/, for example your repository is at https://github.com/<USERNAME>/<REPO>, then set base to '/<REPO>/'.
