### ISSUE TITLE
.well-known

### ISSUE THREAD

**Issue by bennypowers** [actions/upload-pages-artifact#37]
My 11ty site builds a `.well-known/webfinger` file. I'd like to upload that, but it does not get added to the upload archive. I've tried to fix by adding `.nojekyll` to root and by adding `_config.yml` containing `include: ['.well-known']`, as per https://github.com/tschaub/gh-pages/issues/381.

Please add an `include` input, or some such.

Thanks.

**Comment by yoannchaudet** [comment]
Can you share your repo?

**Comment by bennypowers** [comment]
https://github.com/bennypowers/bennypowers.dev/actions/runs/3555611761/jobs/5972409947

turns out it was my fault: https://github.com/bennypowers/bennypowers.dev/blob/99b6cfdc5ae97dc39cb2677949fce6ca00bf5485/eleventy.config.cjs#L26

for one reason or another, 11ty wasn't consistently building that file in CI. This was the fix.
