### ISSUE TITLE
Don't change file permissions of other files

### ISSUE THREAD

**Issue by hfhbd** [actions/upload-pages-artifact#43]
I don't know why do you change the file permissions at all, but you should:
- only change the permissions of files specified in the `INPUT_PATH`
- or ideally instead of changing the permissions at all, copy the files first, change the permission and upload the copy

Current behavior: 
This action changes the permission of other irrelevant files in the root directory.
```
Run chmod -c -R +rX . | while read line; do
chmod -c -R +rX . | while read line; do
    echo "::warning title=Invalid file permissions automatically fixed::$line"
  done
  tar \
    --dereference --hard-dereference \
    --directory "$INPUT_PATH" \
    -cvf "$RUNNER_TEMP/artifact.tar" \
    --exclude=.git \
    --exclude=.github \
    .
  shell: /usr/bin/sh -e {0}
  env:
    GITHUB_PAGES: true
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.5-8/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.5-8/x64
    GRADLE_BUILD_ACTION_SETUP_COMPLETED: true
    GRADLE_BUILD_ACTION_CACHE_RESTORED: true
    INPUT_PATH: build/customRepo
Warning: mode of './.gradle/configuration-cache/3d4ezqthbivz3wwv9taouy8rt' changed from 0700 (rwx------) to 0755 (rwxr-xr-x)
Warning: mode of './.gradle/configuration-cache/3d4ezqthbivz3wwv9taouy8rt/buildfingerprint.bin' changed from 0600 (rw-------) to 0644 (rw-r--r--)
...
````

**Comment by KyeRussell** [comment]
The resulting annotations/warnings definitely made me shudder as they referred to files which should definitely be private, in the context of a workflow that was responsible for publishing things...publicly.

If—for whatever reason—this _is_ necessary, the use of warnings should be reconsidered.
