### ISSUE TITLE
Unnecessary permission updates for files

### ISSUE THREAD

**Issue by rajsite** [actions/upload-pages-artifact#45]
When using [upload-pages-artifacts@v1](https://github.com/ni/nimble/blob/3778ccc5ff750abea1b6808e5df8b70c5461a122/.github/workflows/main.yml#L55) I get warnings about updating permissions for the following **files** from permissions 0744 to 0755:

```bash
Warning: mode of 'packages/site/dist/storybook/blazor-client-app/wwwroot/_framework/dotnet.wasm' changed from 0744 (rwxr--r--) to 0755 (rwxr-xr-x)
Warning: mode of 'packages/site/dist/storybook/blazor-client-app/wwwroot/_framework/dotnet.6.0.11.agdggo08ph.js' changed from 0744 (rwxr--r--) to 0755 (rwxr-xr-x)
Warning: mode of 'packages/site/dist/storybook/blazor-client-app/wwwroot/_framework/icudt_EFIGS.dat' changed from 0744 (rwxr--r--) to 0755 (rwxr-xr-x)
Warning: mode of 'packages/site/dist/storybook/blazor-client-app/wwwroot/_framework/Faker.NETCore.dll' changed from 0744 (rwxr--r--) to 0755 (rwxr-xr-x)
Warning: mode of 'packages/site/dist/storybook/blazor-client-app/wwwroot/_framework/icudt_CJK.dat' changed from 0744 (rwxr--r--) to 0755 (rwxr-xr-x)
Warning: mode of 'packages/site/dist/storybook/blazor-client-app/wwwroot/_framework/icudt_no_CJK.dat' changed from 0744 (rwxr--r--) to 0755 (rwxr-xr-x)
Warning: mode of 'packages/site/dist/storybook/blazor-client-app/wwwroot/_framework/blazor.webassembly.js' changed from 0744 (rwxr--r--) to 0755 (rwxr-xr-x)
Warning: mode of 'packages/site/dist/storybook/blazor-client-app/wwwroot/_framework/icudt.dat' changed from 0744 (rwxr--r--) to 0755 (rwxr-xr-x)
Warning: mode of 'packages/site/dist/storybook/blazor-client-app/wwwroot/_framework/de-DE/Faker.NETCore.resources.dll' changed from 0744 (rwxr--r--) to 0755 (rwxr-xr-x)
Warning: mode of 'packages/site/dist/storybook/blazor-client-app/wwwroot/_framework/dotnet.timezones.blat' changed from 0744 (rwxr--r--) to 0755 (rwxr-xr-x)
```

I don't fully understand why the permissions of files are being changed as it looks like the command is targeting directories:

https://github.com/actions/upload-pages-artifact/blob/253fd476ed429e83b7aae64a92a75b4ceb1a17cf/action.yml#L24

Regardless, for the use case I am hitting maybe the action should just update permissions for the current user (which these files already had the correct permissions for)?:

```bash
chmod -c -R u+rX "$INPUT_PATH" | while read line; do
```

Another alternative would be to add a parameter to the action to suppress the warnings in my summary logs (I don't mind them in the logs but the `::warning` annotation is making the build summary noisy).

**Comment by yoannchaudet** [comment]
Hello,

Today these show as warnings in your logs but very soon (if not already), we will be rejecting artifacts with incorrect permissions (on the server side).

The warnings are a red hearing that something in your build process is not creating files in a way we expect (currently). Adding a `chmod` step yourself will make the warnings go away.

**Comment by rajsite** [comment]
But just to confirm, do the warning messages being output actually seem reasonable. The permissions are being updated from 0744 to 0755, is that actually necessary? The user level already has full permissions which seems like the intent of the script.

![image](https://user-images.githubusercontent.com/1588923/214640369-956001dc-9970-4b4d-9c09-86568ab75016.png)

**Comment by JamesMGreene** [comment]
Updates: 🚀 

- The `chmod` removal has been reverted in [`v1.0.10`](https://github.com/actions/upload-pages-artifact/releases/tag/v1.0.10) and the latest `v1` major tag
- The `chmod` removal has been reapplied in [`v2.0.0`](https://github.com/actions/upload-pages-artifact/releases/tag/v2.0.0) and the new `v2` major tag
