### ISSUE TITLE
Artifacts uploaded are not removed on server causing storage limit.

### ISSUE THREAD

**Issue by m-nathani** [actions/upload-pages-artifact#50]
I used the action to upload my website docs on github-pages. However, each deployment created an artifact of **2GB** causing my storage on github to reach its max capacity.

Should there be a way to delete the artifacts in the action after it deploys to pages ?

Maybe if its possible to on `post` actions of `upload-pages-artifact`

**Comment by yoannchaudet** [comment]
Hello!

We actually do remove artifacts from the backend side for you. I believe we only keep the last few ones (between 1 and 3). We also set the retention on the artifact to the minimum we can which is a day. The billing meters around artifacts storage are also not real time so unless you build many times in a single day, you should only see a temporary impact on your storage (for private repositories).

**Comment by m-nathani** [comment]
@yoannchaudet hey I did tried using .. and checked the default retention is 1 day... However the size of our build is big so we wanted to delete the artifact immediately.


Which I did not found
