### ISSUE TITLE
Unable to specify correct build folder path for upload

### ISSUE THREAD

**Issue by basher** [actions/upload-pages-artifact#67]
I have a repo with Storybook-HTML, which I'm trying to publish with GitHub Pages.

Here's my YAML actions file:
https://github.com/basher/Web-UI-Boilerplate/blob/master/.github/workflows/static.yml 

The **BUILD** succeeds, and outputs the static Storybook files as shown in screenshot:

![build](https://github.com/actions/upload-pages-artifact/assets/452809/8bbbe287-d9f6-4d1b-9792-24a66027264d)

The **UPLOAD** always fails with this error:

![upload](https://github.com/actions/upload-pages-artifact/assets/452809/ca33fa55-1fdb-4e77-bdd1-f8b0fddc67bb)

I have tried all the different permutations for specifying the **PATH**... for example, with/without quotes, with absolute URL, etc.

Any help will be much appreciated!

**Comment by yoannchaudet** [comment]
@basher You need to move the [upload step](https://github.com/basher/Web-UI-Boilerplate/blob/9538298dbcd310b2f34fbcd09f4b708d3118a8ff/.github/workflows/static.yml#L42-L46) in the build job.

Jobs don't share files between each others, hence artifacts ;)

**Comment by basher** [comment]
@yoannchaudet Thanks, that worked.

I also had to qualify the path with the current workspace:
`path: ${{ github.workspace }}/ui/storybook-static`
