### ISSUE TITLE
Can the name of the generated artifact be changed?

### ISSUE THREAD

**Issue by 6a6f6a6f** [actions/upload-pages-artifact#75]
I'm having an issue where the org changed the repo which has this action, and the generated artifact name still points to the previous one, generating an invalid path on the page environment, for example:

- The previous name of the repo was `my-cool-repo`
- Now is `my-not-cool-repo`

And the deploy path is `user.github.io/my-cool-repo` instead of `user.github.io/my-not-cool-repo`.

Thanks for any help (even if it is an RTFM situation).

**Comment by JamesMGreene** [comment]
Hello! 👋 

This action is responsible for the artifact that get used to deploy the Pages site, but is not responsible for the URL path that Pages uses. 🙅 

That said, Pages deploy path for a renamed repo should update pretty quickly after the rename event. It should definitely be correct by the next deployment of the Pages site at the very least.

However, you may find that the old path continues to work as well at least temporarily or until a new deploy to the old URL overrides it, so both paths may be available at least temporarily.

Please let us know if that's not what you're experiencing. 🤔
