### ISSUE TITLE
Support actions/download-artifact@v4

### ISSUE THREAD

**Issue by tustvold** [actions/upload-pages-artifact#83]
It would appear that the latest release of actions/download-artifact has made breaking change to where it looks for uploads.

https://github.com/actions/download-artifact#breaking-changes

https://github.com/actions/download-artifact/issues/250

This appears to make it incompatible with this action - https://github.com/apache/arrow-rs/actions/runs/7223753149/job/19683516143

**Comment by yoannchaudet** [comment]
We published [v3](https://github.com/actions/upload-pages-artifact/releases/tag/v3.0.0) a few days ago which should fix that.
