### ISSUE TITLE
release notes for 3.0.0 say `his [sic] version`

### ISSUE THREAD

**Issue by jsoref** [actions/upload-pages-artifact#84]
https://github.com/actions/upload-pages-artifact/releases/tag/v3.0.0 says:
> To deploy a GitHub Pages site which has been uploaded with _his_ version of actions/upload-pages-artifact, you must also use actions/deploy-pages@v4 or newer.

It should probably be `this version`...

**Comment by yoannchaudet** [comment]
Good 👀!

Thank you for catching that. It's fixed.
