### ISSUE TITLE
Node.js 16 actions deprecated and what should I do?

### ISSUE THREAD

**Issue by ahyangyi** [actions/upload-pages-artifact#90]
Github has been complaining that `actions/upload-artifact@v2` and `actions/upload-artifact@v3` being node.js 16 actions and deprecated. I don't think you have any newer version around though... so what should I do?

**Comment by SilverRainZ** [comment]
https://github.com/actions/upload-pages-artifact/releases/tag/v3.0.0 updates upload-artifact to v4, may be helpful to you.

**Comment by JamesMGreene** [comment]
As @SilverRainZ helpfully mentioned, you can use `actions/upload-pages-artifact@v3.0.0` (or `@v3`) to move past the Node 16.x deprecation warnings.
