### ISSUE TITLE
Setting custom 404 page not working

### ISSUE THREAD

**Issue by zefir-git** [actions/upload-pages-artifact#93]
As per [Creating a custom 404 page for your GitHub Pages site](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site), having a `.github/404.html` should work as a custom 404 page.

However, when publishing from a subdirectory (`dist`) using this action, the 404 page is still the default GitHub Pages one. I also tried copying the `.github/404.html` file to `dist/.github/404.html` inside the workflow with:
```yaml
 - run: mkdir dist/.github && cp .github/404.html dist/.github/404.html
```
However, that did not seem to work either.

In the `Upload Artifact` step an `Run tar` I do not see this file being included. Is it possible that directories beginning with a dot are not included in the tarball? Am I even supposed to put `.github/404.html` inside my `dist` to create a custom 404 page?

**Comment by yoannchaudet** [comment]
The file should be at the root of your archive not under a `.github` folder.

**Comment by yoannchaudet** [comment]
Right in the link you referenced initially 😁

https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site
